---
- hosts: all
  gather_facts: false
  vars:
     DiskThreshold: 45

  tasks:
  - name: run PS_Script
    ansible.windows.win_shell: C:\temp\PS_Scripts\FreeSpace.ps1

  - name: copy disk space information from file
    ansible.windows.win_shell:
      Select-String -Path C:\temp\FreeSpace.txt -pattern "@{FreeSpace="
    register: freespace

  - name: read file to get free disk space
    set_fact: freediskspace={{ freespace.stdout_lines }}

  - name: trim file to get free disk space value
    set_fact: data1={{ freediskspace | regex_replace('.*=') | regex_replace ("'.*") }}

  - name: check if disk space above threshold
    set_fact:
     DiskSpace:
       "{{ (DiskThreshold | int) >= (data1 | int) }}"

  - name: copy servername text from file
    ansible.windows.win_shell:
       Select-String -Path C:\temp\Servername.txt -pattern "Server="
    register: servername

  - name: read file to get server name
    set_fact: servername1={{ servername.stdout_lines }}

  - name: trim file to get servername value
    set_fact: name={{ servername1 | regex_replace('.*=') | regex_replace ("'.*") }}

  - name: Disk Space Information
    debug:
      msg:
        - "***********************************************************"
        - "{{ name }} has only {{ data1 }}GB free on the C Drive"
        - "Free up some Space on the C Drive before patching commences"
        - "***********************************************************"
    when: DiskSpace is true
