---
- hosts: all
  gather_facts: false
  vars_prompt:
  - name: patch_number1
    prompt: What is the patch number?
    private: no

 tasks:
  - name: Check if Patch installed
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: Get-Hotfix {{ patch_number1 }}
    register: result_patch_installed

  - debug:
      msg: " {{ result_patch_installed }} "

  - debug:
      msg: " Patch is installed - yipee "
    when: result_patch_installed == true

  - debug:
      msg: " Patch is not installed - boo hoo "
    when: result_patch_installed != true

#   check if patch number2 = 0 - if so stop, else check patch 2 as avove
#  also need to try and get the server name on ths file
