---
- hosts: all
  gather_facts: false
  tasks:
#
#   copy the powershell file AutoServices.ps1 to C:\TEMP\ on the server
#
  - name: run PS_Script AUTOSERVICES.PS1
    ansible.windows.win_shell: C:\temp\PS_Scripts\AutoServices.ps1

  - name: pause tasks for 5 seconds to allow the script to run
    ansible.builtin.pause:
      seconds: 5
      prompt: Waiting for script to run, please wait!

  - name: Get number of services to restart
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: (Get-Content C:\temp\autoservices.txt).Length
    register: auto_services

  - name: user powershell to add "1" to the number of times to run the loop
    win_shell: "{{ auto_services.stdout_lines[0] }} + 1"
    register: auto_services_num

  - name: identify number of times to run the loop
    set_fact: loop_num={{ auto_services_num.stdout_lines[0]|int}}

  - name: set_fact to check if a service has failed to restart
    set_fact: service_failed="false"

  - name: bob
    ansible.builtin.debug:
      msg: "service_failed = {{ service_failed }}"

  - name: restart all the Auto Services that require to be restarted
    include_tasks: restart_auto_services.yml
    loop: "{{ range(1,(loop_num|int)) | list }}"

  - name: bob2
    ansible.builtin.debug:
      msg: "service_failed = {{ service_failed }}"

  - name: all AUTO services are now started after the reboot
    ansible.builtin.debug:
      msg: "all AUTO services are started after the reboot"
    when: "{{ service_failed}}" == "True"

  - name: write entry to the windows event log
    win_eventlog_entry:
      log: Application
      source: Ansible
      event_id: 1971
      message: All AUTO Services are started after rebooted
    when: service_failed == "False"
