---
- hosts: all
  gather_facts: false
  vars_prompt:
  - name: patch_number
    prompt: What is the patch number?
    private: no

  tasks:
  - name: Get server name
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: hostname
    register: server_name

  - name: Check if Patch installed
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: Get-Hotfix {{ patch_number }}
    register: result_patch_installed
    ignore_errors: true

  - name: set the fact
    set_fact: patch={{ result_patch_installed.stdout_lines }}

  - debug:
      msg: " {{ patch_number }} is installed on {{ server_name.stdout_lines[0] }} "
    when: patch|length > 2

  - debug:
      msg: " {{ patch_number }} is not installed on {{ server_name.stdout_lines[0] }}"
    when: patch|length < 1

  - name: write to file
    lineinfile:
      dest: /ansible/ian.conf
      line: "is installed on" 
      create: yes
      state: present
