---
- hosts: all
  gather_facts: false
  vars_prompt:
  - name: patch_number
    prompt: What is the patch number?
    private: no

  tasks:
  - name: Get server name
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: hostname
    register: server_name

  - name: Check if Patch installed
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: Get-Hotfix {{ patch_number }}
    register: patch_installed
    ignore_errors: true

  - debug:
      msg: " {{ patch_installed }} is installed on {{ server_name.stdout_lines[0] }} "
    when: patch2|length > 2

  - debug:
      msg: " {{ patch_installed }} is not installed on {{ server_name.stdout_lines[0] }}"
    when: patch2|length < 1
