---
- hosts: all
  gather_facts: false
  vars_prompt:
  - name: patch_number1
    prompt: What is the patch number?
    private: no

  tasks:
  - name: Check if Patch installed
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: Get-Hotfix {{ patch_number1 }}
    register: result_patch_installed
    ignore_errors: true

  - name: set the fact
    set_fact: patch1={{ result_patch_installed.stdout_lines }}

  - debug:
      msg: " {{ patch_number1 }} is installed - yipee "
    when: patch1|length > 2

  - debug:
      msg: " {{ patch_number1 }} is not installed - boo hoo "
    when: patch1|length < 1

#   check if patch number2 = 0 - if so stop, else check patch 2 as avove
#  also need to try and get the server name on ths file
