---
- hosts: all
  gather_facts: false
  tasks:

#    - name: copy file from Windows to Windows
#      ansible.windows.win_copy:
#        src: C:\temp\ian.txt
#        dest: C:\temp\a\ian.txt
#        remote_src: yes

    - name: copy file from windows to centos
#     copy file to HOME/IAN/FILES/192.168.1.82/C:/TEMP/IAN.TXT
#     if you have flat:yes, copies to HOME/IAN/FILES/*.PS1
      fetch:
        src: C:/temp/Applicable_Patches1.ps1
#        dest: /home/files/192.168.1.249
        dest: /home/ian/files/
#        dest: /ansible-files/
        flat: yes
        remote_src: yes

    - name: file copy1
      fetch:
        src: C:\temp\installed_Patches.ps1
        dest: /home/ian/files/
        remote_src: yes

    - name: file copy2
      fetch:
        src: C:\temp\Patch_Extract.ps1
        dest: /home/ian/files/
        remote_src: yes

    - name: file copy3
      fetch:
        src: C:\temp\Patching_Merge.ps1
        dest: /home/ian/files/
        remote_src: yes

#    - name: copy ansible directory from centos to windows
#      win_copy:
#        src: /ansible-files/
#        dest: C:\WSUS\
