---
- hosts: all
  gather_facts: false
  tasks:

  - name: write to file
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: 127.0.0.1 localhost
      owner: root
      group: root
      mode: '0644'
