---
- hosts: all
  gather_facts: no
  tasks:

  - name: gather limited facts
    setup:
      filter: "ansible_facts['reboot_pending']"

  - name: default gateway
    debug:
      msg: "{{ ansible_facts['uptime_seconds] }}"

  - name: set_fact
    set_fact: uptime={{ ansible_facts['uptime_seconds'] }}

  - name: reboot server
    debug:
      msg: "server wants a reboot"
    when: uptime | int >= 5000
