---
- hosts: all
  gather_facts: yes
  tasks:

  - name: print facts
    debug:
      var: ansible_facts

#  - name: default gateway
#    debug:
#      msg: "{{ ansible_facts['interfaces'][0]['default_gateway'] }}"

  - name: uptime_seconds
    debug:
      msg: "{{ ansible_facts['uptime_seconds'] }}"

  - name: pending_reboot
    debug:
      msg: "{{ ansible_facts['reboot_pending'] }}"      
