---
- hosts: all
  gather_facts: false
  tasks:
#
#   copy the powershell file to C:\TEMP\ on the server
#
#
  - name: run PS_Script AUTOSERVICES.PS1
    ansible.windows.win_shell: C:\temp\PS_Scripts\AutoServices.ps1

  - name: pause tasks for 5 seconds to allow the script to run
    ansible.builtin.pause:
      seconds: 5
      prompt: Waiting for script to run, please wait!

  - name: Get number of services to restart
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: (Get-Content C:\temp\autoservices.txt).Length
    register: auto_services

  - name: user powershell to add "1" to the number of times to run the loop
    win_shell: "{{ auto_services.stdout_lines[0] }} + 1"
    register: auto_services_num

  - name: identify number of times to run the loop
    set_fact: loop_num={{ auto_services_num.stdout_lines[0]|int}}

  - name: do a loop
    include_tasks: tasks1c.yml
    loop: "{{ range(1,(loop_num|int)) | list }}"
