
---
- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - block:

        - name: Check Service is running - if not , start it
          ansible.windows.win_service:
            name: spooler
            state: started
          register: status

        - debug:
            msg: " Windows Update service is running "
          when: status.failed == false

      rescue:
        - debug:
            msg: " Windows Update service is stopped and didn't restart "

        - name: kill process of service
          win_command: taskkill /FI "SERVICES eq spooler" /F
          register: result_process_kill

        - name: pause tasks for 20 seconds
          ansible.builtin.pause:
            seconds: 20
            prompt: Waiting for taskkill command, please wait!
          when: result_process_kill == true

        - name: Re-Check spooler
          ansible.windows.win_service:
            name: spooler
            state: started
          register: status

        - debug:
            msg: " Windows Update service is running "
          when: status.failed == false

        - debug:
            msg: " Windows Update service is stopped and didnt restart - please investigate "
          when: status2.failed == true
