---
- hosts: all
  gather_facts: false
  tasks:

  - name: run several tasks
    include_tasks: "{{ item1 }}"
    loop:
      - loop2.yml
      - loop3.yml
      - loop4.yml
    loop_control:
      index_var: item1  
