---
- hosts: node1
  gather_facts: false
  become: yes
  become_user: root
  vars:
    source: /home/ansible/automation
    destination: /home/ansible/merged_data/windows_patch_info.csv
# Create folder structure incase its disappears
  tasks:
  - name: Create /home/ansible/merged_data if it does not exist
    ansible.builtin.file:
      path: /home/ansible/merged_data
      state: directory
      mode: '0755'
  - name: Create /home/ansible/automation if it does not exist
    ansible.builtin.file:
      path: /home/ansible/automation
      state: directory
      mode: '0755'
# To be added shortly.  Post patching playbook will zip all endpoint reports
# This playbook with unzip via gunzip *.gz
# Remove previous merged report
  - name: Remove merged file
    ansible.builtin.file:
      path: /home/ansible/merged_data/windows_patch_info.csv
      state: absent
# Merge all endpoint reports into one csv
  - name: Merge raw contents from all data filesystem
    assemble:
      src: "{{ source }}"
      dest: "{{ destination }}"
# Below datestamp code will be replaced with simple version when running from toweradmin
# simple code will not run via Ansible in a Box
  - name: datestamp for archive file
    shell: "date +%Y-%m-%d%H-%M-%S"
    register: tstamp
  - name: Set var for datestamp
    set_fact:
     cur_date: "{{ tstamp.stdout[0:10]}}"
     cur_time: "{{ tstamp.stdout[10:]}}"
# Archive and datestamp windows_patch_info.csv
  - name: Archive to gz file type
    archive:
      path: /home/ansible/merged_data/windows_patch_info.csv
      dest: "/home/ansible/merged_data/PatchingReport-{{ cur_date }}:{{ cur_time }}.gz"
      format: gz
# QUESTION - How long do we want to keep the archived files for?
  - name: Housekeeping - Find archives older than 1 year
    find:
      paths: /home/ansible/merged_data
      age: 56w
      recurse: yes
    register: filesOlderThan1Y
  - name: Housekeeping - Remove archives older than 1 year
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ filesOlderThan1Y.files }}"
