---
- hosts: all
  gather_facts: false
  tasks:

  - name: search
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
      state: searched
      log_path: c:\temp\missing_patches.txt
    register: patch

#  - name: search
#    win_updates:
#      category_names: "{{ item }}"
#      state: searched
#      log_path: c:\temp\missing_patches.txt
#    register: patch
#    with_items:
#        - SecurityUpdates
#        - CriticalUpdates

  - name: Check
    debug:
      msg: "{{ patch }}"

  - name: check 2 - filtered_updates
    debug:
      msg: "{{ patch.filtered_updates }}"

  - name: check 3 - updates
    debug:
      msg: "{{ patch.updates }} "

#  - name: check 4 - updates
#    debug:
#      msg: "{{ patch.updates.73f45b23-8537-455d-83fd-840e7e93b835.kb }}"

  - name: copy information to local machine
    win_copy:
      content: "{{ patch.updates }}"
      dest: "c:/temp/patch_updates.csv"
      remote_src: yes

  - name: copy information to local machine
    win_copy:
      content: "{{ patch.filtered_updates }}"
      dest: "c:/temp/patch_filtered_updates.csv"
      remote_src: yes
