---
- hosts: all
  gather_facts: false
  tasks:

  - name: search
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
      state: searched
      log_path: c:\temp\missing_patches.txt
    register: patch

#  - name: search
#    win_updates:
#      category_names: "{{ item }}"
#      state: searched
#      log_path: c:\temp\missing_patches.txt
#    register: patch
#    with_items:
#        - SecurityUpdates
#        - CriticalUpdates

  - name: Check
    debug:
      msg: "{{ patch }}"

  - name: check 2 - filtered_updates
    debug:
      msg: "{{ patch.filtered_updates }}"

  - name: check 3 - updates
    debug:
      msg: "{{ patch.updates }} "

  - name: check 4 - updates
    debug:
      msg: "{{ patch.updates }} "a711f6a5-5bf3-4392-95d0-686f748789dd.kb "    

  - name: copy information to local machine
    win_copy:
      content:
        - " {{ inventory_hostname }} ,"
        - " {{ patch.updates }}"
        - " hello "
        - " {{ patch.updates }}"
      dest: "c:/temp/imc_patch.csv"
      remote_src: yes

  - name: insertline
    lineinfile:
      dest: c:/temp/imc_patch1.txt
      line: ' added this file '
