---
- hosts: all
  gather_facts: false
  tasks:

  #- name: search
  #  win_updates:
  #    category_names:
  #      - SecurityUpdates
  #      - CriticalUpdates
  #    state: searched
  #    log_path: c:\temp\missing_patches.txt
  #  register: missing_patch_count

  - name: search
    win_updates:
      category_names: " {{ item }}"
      state: searched
      log_path: c:\temp\missing_patches.txt
    register: missing_patch_count
    with_items:
        - SecurityUpdates
        - CriticalUpdates

  - name: missing patches
    debug:
      msg: "{{ missing_patch_count.results }}"

  - name: missing patches(1)
    debug:
#      msg: " {{ missing_patch_count.reults.kb }}"
      msg: " {{ item.kb }}"

#  - name: missing patches(2)
#    debug:
#      msg:
#        - " {{ missing_patch_count.filtered_updates }} "
#        - " {{ missing_patch_count.updates }} "

  - name: missing_patches(3)
    debug:
      msg: " {{ missing_patch_count.updates[1].kb }} "

  - name: copy information to local machine
    win_copy:
      content:
        - " {{ inventory_hostname }} ,"
        - " {{ missing_patch_count.updates }}"
        - " hello "
        - " {{ missing_patch_count.updates }}"
      dest: "c:/temp/imc_patch.csv"
      remote_src: yes

  - name: insertline
    lineinfile:
      dest: c:/temp/imc_patch1.txt
      line: ' added this file '
