---
- hosts: all
  gather_facts: false
  tasks:

  - name: search
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
      state: searched
      log_path: c:\temp\missing_patches.txt
    register: missing_patch_count

  - name: missing patches
    debug:
      msg: "{{ missing_patch_count }}"

#  - name: missing patches(1)
#    debug:
#      msg: " {{ missing_patch_count.updates }}"

  - name: missing patches(2)
    debug:
      msg:
        - " {{ missing_patch_count.filtered_updates }} "
        - " {{ missing_patch_count.updates }} "

#  - name: missing_patches(3)
#    debug:
#      msg: " {{ item.kb }} "
#    loop: " {{ missing_patch_count.filtered_updates }}"
  #    msg: " {{ missing_patch_count.updates_kb }}"

  - name: copy information to local machine
    win_copy:
      content:
        - " {{ inventory_hostname }} ,"
        - " {{ missing_patch_count.updates }}"
        - " hello "
        - " {{ missing_patch_count.updates }}"
      dest: "c:/temp/imc_patch.csv"
      remote_src: yes
