---
- hosts: all
  gather_facts: false
  tasks:

  - name: search
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
      state: searched
      log_path: c:\temp\missing_patches.txt
    register: patch

#  - name: search
#    win_updates:
#      category_names: "{{ item }}"
#      state: searched
#      log_path: c:\temp\missing_patches.txt
#    register: patch
#    with_items:
#        - SecurityUpdates
#        - CriticalUpdates

  - name: Check
    debug:
      msg: " {{ patch }}"

  - name: check 2
    debug:
      msg: " {{ patch.updates[0] }}"

#  - name: missing patches(2)
#    debug:
#      msg:
#        - " {{ missing_patch_count.filtered_updates }} "
#        - " {{ missing_patch_count.updates }} "

  - name: missing_patches(3)
    debug:
      msg: " {{ missing_patch_count.updates[1].kb }} "

  - name: copy information to local machine
    win_copy:
      content:
        - " {{ inventory_hostname }} ,"
        - " {{ missing_patch_count.updates }}"
        - " hello "
        - " {{ missing_patch_count.updates }}"
      dest: "c:/temp/imc_patch.csv"
      remote_src: yes

  - name: insertline
    lineinfile:
      dest: c:/temp/imc_patch1.txt
      line: ' added this file '
