---
- hosts: all
  gather_facts: false
  vars:
     days: 50
     server_location: 192.168.1.249
  tasks:
#
# These 3 sections will create the file C:\TEMP\{{sever_name_applicable.csv}} on the server
#
#- name: download Missing_Patches.ps1 file from bds server
#  win_get_url:
#    url: https://10.177.57.227:8081/repository/lbg/temp/patching/Missing_Patches.PS1
#    dest: c:\temp
#    validate_certs: no
#  register: file_copy1

  - name: copy Applicable_Patches.ps1 from centos to windows
    win_copy:
      src: /ansible/PS_Scripts/Applicable_Patches.PS1
      dest: C:\temp\Applicable_Patches.ps1
    register: file_copy1

  - name: download failed
    fail:
      msg: " ### Applicable_Patches.ps1 file download failed - please investigate *** "
    when: file_copy1.failed == true

  - name: run PS_Script Applicable_Patches.PS1
    win_shell: C:\temp\Applicable_Patches.ps1
#
# These 3 sections will create the file C:\TEMP\{{sever_name_installed.csv}} on the server - conatains all patches installed
#
#- name: download Installed_Patches.ps1 file from bds server
#  win_get_url:
#    url: https://10.177.57.227:8081/repository/lbg/temp/patching/Installed_Patches.PS1
#    dest: c:\temp
#    validate_certs: no
#  register: file_copy2

  - name: copy Installed_Patches.ps1 from centos to windows
    win_copy:
      src: /ansible/PS_Scripts/Installed_Patches.PS1
      dest: C:\temp\Installed_Patches.ps1
    register: file_copy2

  - name: download failed
    fail:
      msg: " ### installed_Patches.ps1 file download failed - please investigate *** "
    when: file_copy2.failed == true

  - name: run PS_Script Installed_Patches.PS1
    win_shell: C:\temp\Installed_Patches.ps1
#
# These 3 sections will create the file to identify what patches were installed on the server in the last 30 days
# Then it will merge the data with c:\temp\{{serer_name_applicable.csv}}
#
#- name: download Patch_Extract.ps1 file from bds server
#  win_get_url:
#    url: https://10.177.57.227:8081/repository/lbg/temp/patching/Patch_Extract.PS1
#    dest: c:\temp
#    validate_certs: no
#  register: file_copy3

  - name: copy Patch_Extract.ps1 from centos to windows
    win_copy:
      src: /ansible/PS_Scripts/Patch_Extract.PS1
      dest: C:\temp\Patch_Extract.PS1
    register: file_copy3

  - name: download failed
    fail:
      msg: " ### Patch_Extract.ps1 file download failed - please investigate *** "
    when: file_copy3.failed == true

  - name: run PS_Script Patch_Extract.ps1
    win_shell: C:\temp\Patch_Extract.ps1 {{ days }}
#
# These 3 sections will create the file which will merge the Applicable and Extracted Patches to 1 file
# ready to be copied to the SFS server
#
#- name: download Patching_Merge.ps1 file from bds server
#  win_get_url:
#    url: https://10.177.57.227:8081/repository/lbg/temp/patching/Patching_Merge.PS1
#    dest: c:\temp
#    validate_certs: no
#  register: file_copy4
#
  - name: copy Patching_Merge.ps1 from centos to windows
    win_copy:
      src: /ansible/PS_Scripts/Patching_Merge.PS1
      dest: C:\temp\Patching_Merge.PS1
    register: file_copy4

  - name: download failed
    fail:
      msg: " ### Patching_Merge.ps1 file download failed - please investigate *** "
    when: file_copy4.failed == true

  - name: run PS_Script Patching_Merge.ps1
    win_shell: C:\temp\Patching_Merge.ps1

  - name: copy C:\Temp\{{ inventory_hostname}}.csv from Windows host to SFS Server
    win_copy:
#      src: C:\temp\Patch\{{ inventory_hostname }}.csv
      src: C:\temp\Patch\WIN-1D3KJCL01N5.csv
      dest: \\{{ server_location }}\C$\WSUS\Merge\{{ inventory_hostname }}.csv
      remote_src: yes
