---
- hosts: all
  gather_facts: false
  vars:
     days: 30
     server_location: 192.168.1.250
  tasks:

#  - name: search
#    win_updates:
#      category_names:
#        - SecurityUpdates
#        - CriticalUpdates
#      state: searched
#      log_path: c:\temp\missing_patches.txt
#    register: patch
#
#  - name: copy patch_update information to local machine
#    win_copy:
#      content: "{{ patch.updates }}"
#      dest: "c:/temp/patch_updates.txt"
#      remote_src: yes
#
#  - name: copy patch_filtered_update information to local machine
#    win_copy:
#      content: "{{ patch.filtered_updates }}"
#      dest: "c:/temp/patch_filtered_updates.txt"
#      remote_src: yes
#
# These 3 sections will create the file C:\TEMP\{{sever_name_applicable.csv}} on the server
#
#- name: download Missing_Patches.ps1 file from bds server
#  win_get_url:
#    url: https://10.177.57.227:8081/repository/lbg/temp/patching/Missing_Patches.PS1
#    dest: c:\temp
#    validate_certs: no
#  register: file_copy1

  - name: copy Applicable_Patches.ps1 from centos to windows
    win_copy:
      src: /ansible/PS_Scripts/Applicable_Patches.PS1
      dest: C:\temp\Applicable_Patches.ps1
    register: file_copy1

  - name: download failed
    fail:
      msg: " ### Applicable_Patches.ps1 file download failed - please investigate *** "
    when: file_copy1.failed == true

#  - name: run PS_Script Applicable_Patches.PS1
#    win_shell: C:\temp\Applicable_Patches.ps1
#
# These 3 sections will create the file C:\TEMP\{{sever_name_installed.csv}} on the server - conatains all patches installed
#
#- name: download Installed_Patches.ps1 file from bds server
#  win_get_url:
#    url: https://10.177.57.227:8081/repository/lbg/temp/patching/Installed_Patches.PS1
#    dest: c:\temp
#    validate_certs: no
#  register: file_copy2

  - name: copy Installed_Patches.ps1 from centos to windows
    win_copy:
      src: /ansible/PS_Scripts/Installed_Patches.PS1
      dest: C:\temp\Installed_Patches.ps1
    register: file_copy2

  - name: download failed
    fail:
      msg: " ### installed_Patches.ps1 file download failed - please investigate *** "
    when: file_copy2.failed == true

  - name: run PS_Script Installed_Patches.PS1
    win_shell: C:\temp\Installed_Patches.ps1
#
# These 3 sections will create the file to identify what patches were installed on the server in the last 30 days
# Then it will merge the data with c:\temp\{{serer_name_applicable.csv}}
#
#- name: download Patch_Extract.ps1 file from bds server
#  win_get_url:
#    url: https://10.177.57.227:8081/repository/lbg/temp/patching/Patch_Extract.PS1
#    dest: c:\temp
#    validate_certs: no
#  register: file_copy3

  - name: copy Patch_Extract.ps1 from centos to windows
    win_copy:
      src: /ansible/PS_Scripts/Patch_Extract.PS1
      dest: C:\temp\Patch_Extract.PS1
    register: file_copy3

  - name: download failed
    fail:
      msg: " ### Patch_Extract.ps1 file download failed - please investigate *** "
    when: file_copy3.failed == true

  - name: run PS_Script Patch_Extract.ps1
    win_shell: C:\temp\Patch_Extract.ps1 {{ days }}
#
# These 3 sections will create the file which will merge the Applicable and Extracted Patches to 1 file
# ready to be copied to the SFS server
#
#- name: download Patching_Merge.ps1 file from bds server
#  win_get_url:
#    url: https://10.177.57.227:8081/repository/lbg/temp/patching/Patching_Merge.PS1
#    dest: c:\temp
#    validate_certs: no
#  register: file_copy4
#
  - name: copy Patching_Merge.ps1 from centos to windows
    win_copy:
      src: /ansible/PS_Scripts/Patching_Merge.PS1
      dest: C:\temp\Patching_Merge.PS1
    register: file_copy4

  - name: download failed
    fail:
      msg: " ### Patching_Merge.ps1 file download failed - please investigate *** "
    when: file_copy4.failed == true

  - name: run PS_Script Patching_Merge.ps1
    win_shell: C:\temp\Patching_Merge.ps1

  - name: copy C:\Temp\{{ inventory_hostname}}.csv from Windows host to SFS Server
#     copy file to HOME/IAN/FILES/192.168.1.82/C:/TEMP/IAN.TXT
    fetch:
      src: C:\temp\WIN-MHRE3UKN7SQ.csv
      dest: /home/ian/files/
      remote_src: yes
