---
- hosts: all
  gather_facts: false
  vars:
    RebootRequired
  tasks:

  - name: get registry key from server to determine whether a reboot is required
    ansible.windows.win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\{{ RebootRequired }}
#      name: RebootRequired
    register: rebootrequired

  - debug:
      msg: "reboot required = {{ rebootrequired.exists }}"

  - name: Get server name
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: hostname
    register: server_name

  - debug:
      msg: "no reboot required on {{ server_name.stdout_lines[0] }} prior to patching"
    when: rebootrequired.exists == false

  - name: reboot the server as it's pending a rebooted
    block:
      - debug:
          msg: "*** {{ server_name.stdout_lines[0] }} is going to be rebooted prior to patching ***"

#      - name: Reboot server
#        ansible.windows.win_reboot:
#        reboot_timeout: 100
#        register: reboot_status

      - name: Write entry to the windows event log
        win_eventlog_entry:
          log: Application
          source: Ansible
          event_id: 999
          message: Ansible has rebooted the server as it was pending a reboot

      - debug:
          msg: "{{ server_name.stdout_lines[0] }} has been rebooted"

    when: rebootrequired.exists == true
