---
- hosts: all
  gather_facts: false
  vars:

  tasks:

  - name: get registry key from server to determine whether a reboot is required
    ansible.windows.win_reg_stat:
      path: HKLM\Software\Microsoft\Windows\CurrentVersion\Auto Update
      name: RebootRequired
    register: rebootrequired

  - debug:
      msg: "reboot required is {{ rebootrequired }}"

  - debug:
      msg: "needs a reboot"
    when: rebootrequired == true 

  - debug:
      msg: "no reboot needed"
    when: rebootrequired == false


# check if file exists - reboot needed
# check if file does not exist - reboot not reuired

# if it exists - then do a reboot
