---
- hosts: all
  gather_facts: false
  vars:

  tasks:

  - name: get registry key from server to determine whether a reboot is required
    ansible.windows.win_reg_stat:
      path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Auto Update
      name: RebootRequired
    register: rebootrequired

  - name: Get server name
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: hostname
    register: server_name

  - debug:
      msg: "{{ server_name }} is going to be rebooted"
    when: rebootrequired.exists == true

  - debug:
      msg: "no reboot required on {{ server_name }}"
    when: rebootrequired.exists == false
