---
- hosts: all
  gather_facts: false
  vars:

  tasks:
  - name: Reboot server
    win_reboot:
      reboot_timeout: 1
    ignore_errors: true
    register: reboot_status

  - debug:
      msg: "{{ inventory_hostname }} has been rebooted"
    when: reboot_status.failed == false

  - debug:
      msg: "{{ inventory_hostname }} is still being rebooted"
    when: reboot_status.failed == true

  - name: perform when server is not responding from reboot
    block:

    - name: pause for another 5 minutes for server to reboot
      pause:
        seconds: 60

    - name: ping server
      win_ping:
      register: ping_test
      ignore_errors: true

    - debug:
        msg: "{{ inventory_hostname }} has been rebooted"
      when: ping_test.ping == "pong"

    when: reboot_status.failed == true
