---
- hosts: all
  gather_facts: false
  vars:

  tasks:
  - name: Reboot server
    win_reboot:
      reboot_timeout: 1
    ignore_errors: true
    register: reboot_status

  - debug:
      msg: "{{ inventory_hostname }} has been rebooted"
    when: reboot_status.failed == false

  - debug:
      msg: "{{ inventory_hostname }} has not been rebooted"
    when: reboot_status.failed == true

  - name: perform when server is not responding from reboot
    block:
    - name: pause tasks for xx seconds to allow service to be stopped
      pause:
        seconds: 1
        prompt: Waiting for server to reboot

    - name: test play
      win_ping:
      register: ping_test1

    - debug:
        msg: "{{ ping_test1 }}"

    - name: pause tasks for xx seconds to allow service to be stopped
      pause:
        seconds: 10
        prompt: Waiting for server to reboot

    - name: test play
      win_ping:
      register: ping_test2

    - debug:
        msg: "{{ ping_test2 }}"

    when: reboot_status.failed == true
