---
- hosts: all
  gather_facts: false
  vars:

  tasks:
  - name: Reboot server
    win_reboot:
      reboot_timeout: 1
    ignore_errors: true
    register: reboot_status

  - debug:
      msg: "{{ inventory_hostname }} has been rebooted"
    when: reboot_status.failed == false

  - debug:
      msg: "{{ inventory_hostname }} has not been rebooted"
    when: reboot_status.failed == true

#   block
#      pause for 5 minutes
#      ping server
#   when reboot_status.failed == true

  - name: test play
    win_ping:
    register: ping_test1

  - debug:
      msg: "{{ ping_test1 }}"    
