---
- hosts: all
  gather_facts: false
  vars:

  tasks:
  - name: Reboot server
    block:

    - name: reboot server
      win_reboot:
        reboot_timeout: 1
      ignore_errors: true
      register: reboot_status

    - name: server patched, rebooted ok
      debug:
        msg: "server patched and rebooted ok"
      when: reboot_status.failed == false

    rescue:
    - name: server patched, not rebooted
      fail:
        msg: "server patched, server not back"
      when: reboot_status.failed == true
