---
- hosts: all
  gather_facts: false
  vars:

  tasks:

  - name: get registry key
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\reboot
    register: rebootrequired

  - name: Reboot server
    block:

    - name: reboot the server
      win_reboot:
        reboot_timeout: 50
#      ignore_errors: true
      register: reboot_status

    - name: reboot completed
      debug:
        msg: "server patched and rebooted ok"
      when: reboot_status.failed == false

    fail:
    - name: reboot failed
      debug:
        msg: "server patched, server not back"
      when: reboot_status.failed == true

    when: rebootrequired.exists == true

  - name: do the rest of the stuff
    debug:
      msg: "carry on, nothing to see here"
