---
- hosts: all
  gather_facts: false
  vars:

  tasks:
  - name: Reboot server
    win_reboot:
      reboot_timeout: 1
    ignore_errors: true
    register: reboot_status

  - name: perform when server is not responding from reboot
    block:

    - name: pause for another 5 minutes for server to reboot
      pause:
        seconds: 60

    - name: ping server
      win_ping:
      ignore_errors: true

    when: reboot_status.failed == true

  - name: all tickitee boo
    debug:
      msg: "all good in the world"  
