---
- hosts: all
  gather_facts: false
  vars:

  tasks:
  - name: Reboot server
    win_reboot:
      reboot_timeout: 50
    ignore_errors: true
    register: reboot_status

  - name: pause for another 5 minutes for server to reboot
    pause:
      seconds: 60
    when: reboot_status.failed == true

  - name: ping server
    win_ping:
    when: reboot_status.failed == true

  - name: all tickitee boo
    debug:
      msg: "all good in the world"
