---
- hosts: all
  gather_facts: false
  tasks:

  - name: Obtain Information about registry key (short form)
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\currentVersion
    register: current_version

  - name: Obtain Information about registry key property
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\currentVersion
      name: CommonFilesDir
    register: common_files_dir

  - name: Obtain Information about registry key (default)
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\Windows\currentVersion
      name: ' '
    register: current_version_default

  - name: information
    debug:
      msg:
        - "The current_version is {{ current_version }}"
        - "The common files dir is {{ common_files_dir.value }}"
        - "The current_version_default is {{ current_version_default }}"

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\currentVersion
      name: NewStringEntry
      data: "hello"

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\currentVersion
      name: NewDwordEntry
      data: "161171"
      type: dword

  - name: Set maximum policy age
    win_security_policy:
      section: System Access
      key: MaximumPasswordAge
      value: 42

  - name: AmendCachedLogonCounts from 10
    win_security_policy:
      section: Registry Values
      key: MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\CachedLogonsCount
      value: 1,"10"
