---
- hosts: all
  gather_facts: false      
  tasks:
      
#  - name: restart mutiple services - part 1
#    include_tasks: restartmultipleservices2.yml
#    loop:
#      - 'spooler'
#      - 'wuauserv'
#      - 'ian'

  - name: restart multiple services - part 1
    include_tasks: test12.yml
    loop:
      - '*'
