---
  - name: read file to get the service to restart
    ansible.windows.win_shell:
      Select-String -Path C:\temp\autoservices.txt -pattern "Service="
    register: service

  - name: set the fact for the service
    set_fact: service={{ service.stdout_lines[item] }}

  - name: remove everything apart from service name
    set_fact: service_name={{ service | regex_replace('.*=') | regex_replace ("'.*") }}

  - name: restart the Auto service
    block:
      - name: restart the {{ service_name }} service
        ansible.windows.win_service:
          name: "{{ service_name }}"
          state: started
        register: result

      - name: Check Service Status
        ansible.builtin.debug:
          msg: "Service {{ service_name }} has now started"
        when: result.state == "running"

      - name: Write entry to the windows event log if restart successful
        win_eventlog_entry:
          log: Application
          source: Ansible
          event_id: 1971
          message: "{{ service_name }} has been successfully started via Ansible"
        when: result.state == "running"
    rescue:
      - name: service failed to restart correctly
        ansible.builtin.debug:
          msg: "failed to successfully restart the {{ service_name }} service, please investigate"

      - name: set_fact as a service has failed to restart
        set_fact: service_failed="true"
