---
- hosts: all
  gather_facts: false

  tasks:

  - name: Get number of services to restart
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: (Get-Content C:\temp\autoservices.txt).Length
    register: restart_number

  - name: set_fact
    set_fact: req_num2={{ restart_number.stdout_lines[0] }}
  #    req_num= "{{ restart_number.stdout_lines[0] }}"

  - name: set_fact again
    set_fact: req_num3={{ req_num2 | int}}
#      req_num2="{{ req_num }}"

  - set_fact:
      num: 1
      req_num: 3

#  - debug:
#      msg: "req_num2 is {{ req_num3 }}"

  - include_tasks: tasks1.yml
#    loop: "{{ range(num, req_num + 1) | list }}"
    loop: "range(num, {{ req_num3}}) | list"


#    {"msg": "template error while templating string: expected token ':', got '}'
#    . String: {{ range(num, {{ req_num2 }} + 1 ) | list }}"}
