---
- hosts: all
  gather_facts: false
  vars:
    req_num5: 0

  tasks:

  - name: Get number of services to restart
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: (Get-Content C:\temp\autoservices.txt).Length
    register: restart_number

  - name: set_fact
    set_fact: req_num4={{ restart_number.stdout_lines[0] }}

  - name: powershell add 1 to total
    win_shell: "{{ restart_number.stdout_lines[0] }} + 1"
    register: req_num5

  - name: set_fact
    set_fact: req_num6={{ req_num5.stdout_lines[0]|int}}

  - debug:
      msg: "req_num6 is {{ req_num6 }}"

  - name: do a loop
    include_tasks: tasks1c.yml
    loop: "{{ range(1,(req_num6|int)) | list }}"
#    loop: "{{ range(1,10) | list }}"
#    loop: "{{ range(1, {{req_num3) | list }}"
#    loop: "{{ req_num4 }}|list"

#  - include_tasks: tasks1c.yml
#    with_sequence: start=1 end="{{ req_num6 }}"
#    vars:
#      - end_at: "{{ req_num6 }}"

#    when: "item|int < {{ req_num5 }} "
