---
- hosts: all
  gather_facts: false
  vars:
    filepath: c:\temp\autoservicesnumber.txt

  tasks:

  - name: copy text
    ansible.windows.win_shell:
     Select-String -Path C:\temp\autoservicesnumber.txt -pattern "Lines="
    register: string1

  - name: read file, copy data to service
    set_fact: string2={{ string1.stdout_lines }}

  - name: remove everything apart from loop number
    set_fact: string3={{ string2 | regex_replace('.*=') | regex_replace ("'.*") }}

  - name:
    set_fact: req_num={{ string3 | int }}

  - debug:
      msg: "req_num is {{ req_num }}"

  - set_fact:
      num: 1
#      req_num: 3

  - debug:
      msg: "req_num is {{ req_num }}"

#  - set_fact: req_num={{ loopyloop }}

  - include_tasks: tasks1.yml
    loop: "{{ range(num, req_num + 1) | list }}"
