---
- hosts: all
  gather_facts: false

  tasks:

  - name: Get number of services to restart
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: (Get-Content C:\temp\autoservices.txt).Length
    register: restart_number

  - name: set_fact
    set_fact: req_num2={{ restart_number.stdout_lines[0] }}
  #    req_num= "{{ restart_number.stdout_lines[0] }}"


    vars:
      req_num5: {{ req_num2 }}

  - set_fact:
      num: 1
      req_num: 3

#  - debug:
#      msg: "req_num3 is {{ req_num3 }}"

  - include_tasks: tasks1c.yml
    loop: "{{ range(num, req_num5 + 1) | list }}"
#    loop: "{{ range(1,10) | list }}"
#    loop: "{{ range(1, {{req_num3) | list }}"
#    loop: "{{ req_num4 }}|list"


#    {"msg": "template error while templating string: expected token ':', got '}'
#    . String: {{ range(num, {{ req_num2 }} + 1 ) | list }}"}
