---
- hosts: all
  gather_facts: false

  tasks:

  - name: Get number of services to restart
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: (Get-Content C:\temp\autoservices.txt).Length
    register: restart_number

  - set_fact:
      req_num: "{{ restart_number.stdout_lines[0] | join(" ") }}"

  - set_fact:
      num: 1
#      req_num: 3

  - debug:
      msg: "req_num is {{ req_num }}"

  - include_tasks: tasks1.yml
    loop: "{{ range(num, req_num + 1) | list }}"
