---
- hosts: all
  gather_facts: false
  vars_prompt:
  - name: patch_number
    prompt: What is the patch number?
    private: no

  tasks:
  - name: Get server name
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: hostname
    register: server_name

  - name: search file to see if the patch has been installed
    ansible.windows.win_shell:
      Select-String -Path C:\temp\PatchesInstalled.txt -pattern "{{ patch_number}}"
    register: patch

#  - debug:
#      msg: "patch1 is set to {{ patch1 }}"
#
  - name: read file to get free disk space
    set_fact: patch_installed={{ patch.stdout_lines }}
#
#  - debug:
#      msg: "patch2 is set to {{ patch2 }}"

  - debug:
      msg: " {{ patch_number }} is installed on {{ server_name.stdout_lines[0] }} "
    when: patch_installed|length > 2

  - debug:
      msg: " {{ patch_number }} is not installed on {{ server_name.stdout_lines[0] }}"
    when: patch_installed|length < 1
