---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: test play
    win_ping:

  - name: server A debug
    debug:
      msg: "ping server A only"
    with_items: "{{ serverA }}"
#    when: "'serverA' in {{ group_names }}"

  - name: Server B debug
    debug:
      msg: "ping server B only"
    with_items: "{{serverB}}"
#    when: "'serverB' in {{ group_names }}"
