---
- hosts: all
  gather_facts: false
  vars:
     DiskThreshold: 5

  tasks:

  - name: run PS_Script
    ansible.windows.win_shell: C:\temp\PS_Scripts\FreeSpace.ps1

  - name: copy text
    ansible.windows.win_shell:
      Select-String -Path C:\temp\FreeSpace.txt -pattern "@{FreeSpace="
    register: freespace

  - name: read file, copy data to service
    set_fact: freediskspace={{ freespace.stdout_lines }}

  - name: trim rubbish
    set_fact: data1={{ freediskspace | regex_replace('.*=') | regex_replace ("'.*") }}

  - name: blah
    set_fact:
     DiskSpace:
#       "{{ (data1 | int) >= (DiskThreshold | int) }}"
       "{{ (DiskThreshold | int) >= (Data1 | int) }}"

  - name: Information
    debug:
      msg:
        - "Server has only {{ data1 }}GB free on the C Drive"
        - "Free up some Space on the C Drive before patching commences"
    when: DiskSpace is true
