---
- hosts: all
  gather_facts: false
  vars:
    num: 0
  tasks:
      
  - name: restart mutiple services - part 1
    include_tasks: test12.yml
    loop:
      - 'a*'
#    with_items:
#     - 'spool'
#     - 'wuauserv'
#     - 'ian'  
