---
- hosts: all
  gather_facts: false
  vars:
    letter: A
  tasks:

  - name: test play
    win_ping:

- name: Server A only
  hosts: server{{ letter }}
  gather_facts: false

  tasks:
  - name: server A debug
    debug:
      msg: "ping server A only"

- name: server B only
  hosts: serverB
  gather_facts: false

  tasks:

  - name: Server B debug
    debug:
      msg: "ping server B only"
