---
- hosts: noreboot
  gather_facts: true
  tasks:

  - name: First Playbook start
    debug:
      msg: "start of playbook - let's call the roll TEST11 and TEST12"

  - name: call the roll test12
    include_role:
      name:
      - test11
      - test12

  - name: The end
    debug:
      msg: "All done"
