---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: include vars file
    include_vars:
      file: vars.yml

  - name: loop through vars files
    iclude_tasks: test6.yml
    loop: "{{ nodes }}"
