---
- hosts: noreboot
  gather_facts: true
  tasks:

  - name: First Playbook start
    debug:
      msg: "start of playbook - let's call the role TEST11 and TEST12"

  - name: call the roles test11
    include_tasks: test11.yml

  - name: call the roles test12
    include_tasks: test12.yml

  - name: The end
    debug:
      msg: "All done"
