---
- hosts: all
  gather_facts: yes
  tasks:

  - name: debug1
    debug:
      msg: "{{ ansible_ip_addresses }}"
    register: ip

#  - name: set_fact
#    set_fact: ip2={{ ip }}

  - name: remove mac address
#    set_fact: ip1={{ ansible_ip_addresses | regex_replace('.*,') | regex_replace ("'.*") }}
#    set_fact: ip1={{ ip | regex_replace("'","") | regex_replace(",.*","") }}
    set_fact: ip1={{ ip | regex_replace("[","") }}
#    set_fact: ip1={{ ip | regex_replace("ip is ","") }}
#    set_fact: ip1={{ ip | regex_replace(".{5}","") }}

  - name: debug2
    debug:
      msg: "{{ ip1 }}"

  - name: greater than 192.168.1.200
    debug:
      msg: "IP is greater than 192.168.1.200"
    when: ip1 >= "192.168.1.200" and ip1 <= "192.168.1.450"

#  - name: remove everything apart from service name
#    set_fact: service_name={{ service | regex_replace('.*=') | regex_replace ("'.*") }}
