---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: set fact
    set_fact:
      service_name: "IC3 adaptor"

  - name: debug1
    debug:
      msg: "service is equal to IC3 {{ service_name }}"
    when: service_name == "ic3"

  - name: debug2
    debug:
      msg: "service contains the word IC3 {{ service_name }}"
    when: service_name != "ic3"
