---
- hosts: all
  gather_facts: no
  tasks:

  - name: gather limited facts
    setup:
      filter: "ansible_facts['interfaces'][0]['default_gateway']"

  - name: default gateway
    debug:
      msg: "{{ ansible_facts['interfaces'][0]['default_gateway'] }}"

  - name: set_fact
    set_fact: ip2={{ ansible_facts['interfaces'][0]['default_gateway'] }}

  - name: greater than 192.168.1.200 and less than 260
    debug:
      msg: "IP is greater than 192.168.1.200 and less than 260"
    when: ip2 >= "192.168.1.200" and ip2 <= "192.168.1.250"
