---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: test play
    win_ping:

- name: Server A only
  hosts: serverA

  tasks:
  - name: server A debug
    debug:
      msg: "ping server A only"

- name: server B only
  hosts: serverB
  
  tasks:

  - name: Server B debug
    debug:
      msg: "ping server B only"
