---
- hosts: all
  gather_facts: no
  tasks:
  - name: ping
    win_command: ping {{ inventory_hostname }}
    register: ping

  - name: win_ping
    debug:
      msg: "{{ ping.cmd }}"

  - name: set_fact
    set_fact: ip2={{ ansible_facts['interfaces'][0]['default_gateway'] }}

  - name: greater than 192.168.1.200 and less than 192.168.1.260
    debug:
      msg: "{{ ip2 }}"

  - name: greater than 192.168.1.200 and less than 192.168.1.260
    debug:
      msg: "IP is greater than 192.168.1.200"
    when: ip2 >= "192.168.1.200" and ip2 <= "192.168.1.260"
