---
- hosts: all
  gather_facts: false
  tasks:
  - name: ping
    win_command: ping {{ inventory_hostname }}
    register: ping

  - name: debug
    debug:
      msg: " {{ ping }} "  

  - name: regex
    set_fact: ip={{ ping.cmd | regex_replace("ping ","") }}

  - name: greater than 192.168.1.200 and less than 192.168.1.260
    debug:
      msg: "{{ ip }}"

  - name: greater than 192.168.1.200 and less than 192.168.1.260
    debug:
      msg: "IP is greater than 192.168.1.200"
    when: (ip >= "192.168.1.200" and ip <= "192.168.1.250") or (ip >= "192.168.1.252" and ip <= "192.168.1.270")
