---
- hosts: all
  gather_facts: false
  vars:
     service_failed1: false
  tasks:
  - name: set_service_failed to False
    set_fact:
      service_failed: "false"

  - name: debug1
    ansible.builtin.debug:
      msg: "service_failed = {{ service_failed }}"

  - name: debug2
    ansible.builtin.debug:
      msg: "this only happens when it's set to FALSE"
    when: service_failed|bool == false

  - name: set_service_failed to TRUE
    set_fact:
      service_failed: "true"

  - name: debug3
    ansible.builtin.debug:
      msg: "service_failed = {{ service_failed }}"

  - name: debug4
    ansible.builtin.debug:
      msg: "this only happens when it's set to TRUE"
    when: service_failed|bool == true
