---
- hosts: all
  gather_facts: false
  vars:
    num: 0
  tasks:

  - name: debug
    debug:
      msg: "{{ ansible_default_ipv4 }}"

  - name: debug2
    debug:
      msg: "{{ ansible_ssh_host }}"
