---
- hosts: all
  gather_facts: false
  vars:
     number: 0
  tasks:

  - name: set_fact to check if a service has failed to restart
    set_fact: service_failed="false"|bool

  - name: debug1
    ansible.builtin.debug:
      msg: "service_failed = {{ service_failed }}"

  - name: debug2
    ansible.builtin.debug:
      msg: "this only happens when it's set to FALSE"  
    when: service_failed == "false"
