---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: Kill the task
    win_command: cmd.exe -
    args:
      stdin: taskkill /FI "SERVICES eq BITS" /F

  - name: pause the task
    win_command: cmd.exe -
    args:
      stdin: timeout /t 60 /nobreak

#  - name: pause for 10
#    pause:
#      seconds: 10

  - name: debug
    debug:
      msg: "I have waited for 10 seconds"
