---
- hosts: noreboot
  gather_facts: true
  tasks:

  - name: First Playbook start
    debug:
      msg: "start of playbook - let's call the role TEST11 and TEST12"

  - name: call the roles test11 and test12
    include_tasks:
      name: "{{ item }}"
    loop:
      - test11
      - test12

  - name: The end
    debug:
      msg: "All done"
