---
- hosts: all
  gather_facts: false
  vars:
     service_failed: false
  tasks:

  - name: debug1
    ansible.builtin.debug:
      msg: "service_failed = {{ service_failed }}"

  - name: debug2
    ansible.builtin.debug:
      msg: "this only happens when it's set to FALSE"
    when: service_failed == "false" | bool
