---
  - name: read c:\temp\autoservices.txt to get the service to restart
    ansible.windows.win_shell:
      Select-String -Path C:\temp\autoservices.txt -pattern "Service="
    register: service

  - name: set the fact for the service
    set_fact: service={{ service.stdout_lines[item] }}

  - name: remove everything apart from service name
    set_fact: service_name={{ service | regex_replace('.*=') | regex_replace ("'.*") }}

  - name: restart the Auto service
    block:
      - name: restart the {{ service_name }} service
        ansible.windows.win_service:
          name: "{{ service_name }}"
          state: started
        register: result

      - name: Check Service Status
        ansible.builtin.debug:
          msg: "Service {{ service_name }} has now started"
        when: result.state == "running"

      - name: Write entry to the windows event log if restart successful
        win_eventlog_entry:
          log: Application
          source: Ansible
          event_id: 1971
          message: "{{ service_name }} has been successfully started via Ansible"
        when: result.state == "running"
    rescue:
      - name: cheet
        set_fact:
          service_name2: "wuauserv2"

  #    - name: kill process of service
  #      ansible.windows.win_command: cmd.exe -
  #        args:
  #          stdin: taskkill /FI "SERVICES eq {{ service_name }}" /F
  #        register: result_service_kill

      - name: pause tasks for 30 seconds to allow service to be stopped
        ansible.builtin.pause:
          seconds: 1
          prompt: Waiting for taskkill command, please wait!

      - name: restart the {{ service_name2 }} service again
        ansible.windows.win_service:
          name: "{{ service_name2 }}"
          state: started
        register: result2

      - name: Check Service Status
        ansible.builtin.debug:
          msg: "Service {{ service_name2 }} has now started"
        when: result2.state == "running"

      - name: service failed to restart correctly
        ansible.builtin.debug:
          msg: "failed to successfully restart the {{ service_name }} service, please investigate"
        when: result2.state != "running"

      - name: set "service_failed" variable to TRUE
        set_fact:
          service_failed: "true"
        when: result2.state != "running"
