---
- hosts: all
  gather_facts: false
  tasks:

  - name: run PS_Script
    ansible.windows.win_shell: C:\temp\PS_Scripts\FreeSpace.ps1

  - name: copy text
    ansible.windows.win_shell:
      Select-String -Path C:\temp\FreeSpace.txt -pattern "@{FreeSpace="
    register: freespace

  - name: read file, copy data to service
    set_fact: freediskspace={{ freespace.stdout_lines }}

  - name: trim rubbish
    set_fact: data1={{ freediskspace | regex_replace('.*=') | regex_replace ("'.*") }}

  - debug:
      msg: " free disk on server {{ data1 }} "
