---
- hosts: noreboot
  gather_facts: true
  tasks:

    - name: First Playbook start
      debug:
        msg: "start of playbook - let's call the tasks TEST11 and TEST12"

    - name: call the tasks test11 and test12
      include_tasks: test11.yml
#        - "{{ item }}"
#      loop:
#        - "test11.yml"
#        - "test12.yml"

    - name: The end
      debug:
        msg: "All done"
