---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: test play
    win_ping:

  - name: server A debug
    debug:
      msg: "ping server A only"
    when: "inventory_hostname in groups['serverA']"

  - name: Server B debug
    debug:
      msg: "ping server B only"
    when: "inventory_hostname not in groups['serverA']"
