---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: test play
    win_ping:

  - name: Run the "reboot" playbook
    debug:
      msg: "run the 'reboot' playbooks for {{ inventory_hostname }}"
    when: "inventory_hostname in groups['patch']"

  - name: Run the "no reboot" playbook
    debug:
      msg: "run the 'no reboot' playbooks for {{ inventory_hostname }}"
    when: "inventory_hostname not in groups['patch']"
