---
- hosts: all
  gather_facts: false
  tasks:

   - name: get the affected windows host's uptime
     win_shell: "Get-CimInstance-Class CIM_Logicaldisk | Select-Object {$..freespace/1gb}, DeviceID | Where-Object DeviceID -EQ 'C:'"
     register: freespace
