---
- hosts: all
  gather_facts: true
  tasks:

   - name: get the IP Address of the server
     win_command: ping {{ inventory_hostname }}
     register: ping_result

   - name: wot's the IP Address
     debug:
       msg: "IP Address is {{ ping_result.stdout }}"

   - name: debug1
     debug:
       msg: "or the IP Address is {{ ansible_default_ipv4.address }}"
