---
 - name: check service
   ansible.windows.win_service_info:
     name: "{{ item }}"
   register: res1
   ignore_errors: true

 - name: debug
   ansible.builtin.debug:
     msg: "{{res1}}"

 - name: write to file
   community.windows.win_lineinfile:
     path: C:\temp\ian.txt
     line: "Service={{  }}"
     #   when: res1.start_mode == "auto"   
