---
- hosts: all
  gather_facts: false
  vars_prompt:
  - name: patch_number
    prompt: What is the patch number?
    private: no

  tasks:

  - name: run PS_Script
    ansible.windows.win_shell: C:\temp\PS_Scripts\PatchInstalled.ps1

  - name: Get server name
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: hostname
    register: server_name

  - name: search file to see if the patch has been installed
    ansible.windows.win_shell:
      Select-String -Path C:\temp\PatchesInstalled.txt -pattern "{{ patch_number }}"
    register: patch

  - name: read file to get information on patch installed
    set_fact: patch_installed={{ patch.stdout_lines }}

  - debug:
      msg: "patch installed {{ patch_installed }}"

  - block:

    - name: search file to see when the patch was installed
      ansible.windows.win_shell:
        Select-String -Path C:\temp\PatchesInstalled.txt -pattern "{{ patch_number }} InstalledOn="
      register: install_date

    - name: read file to copy installed patch date
      set_fact: installed_on={{ install_date.stdout_lines }}

    - name: trim file to get patch installed date
      set_fact: date={{ installed_on | regex_replace('.*=') | regex_replace ("'.*") }}

    - debug:
        msg: "{{ patch_number }} was installed on {{ server_name.stdout_lines[0] }} on {{ date }}"

    when: patch_installed|length > 2

  - debug:
      msg: " {{ patch_number }} is not installed on {{ server_name.stdout_lines[0] }}"
    when: patch_installed|length < 1
