---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: set fact
    set_fact:
      service_name: "IC3 Adaptor"

  - name: debug1a
    debug:
      msg: "service contains IC3 {{ service_name }}"
    when: service_name != "IC3"

  - name: debug1b
    debug:
      msg: "service does not contain IC4 {{ service_name }}"
    when: service_name != "IC3"

  - name: block section (only run when not IC3)
    block:

      - name: debug2
        debug:
          msg: "debug 2"

      - name: debug3
        debug:
          msg: "debug 3"

      - name: debug4
        debug:
          msg: "debug 4"

    when: service_name != "ic3"
