---
- hosts: all
  gather_facts: false
  vars:
    num: 0
  tasks:
    
  - name: first loop - get data
    include_tasks: test12.yml
    loop:
      - { name: '*', number: {{[1,2,3]}}

  - name: Second loop - use the data from above
    include_tasks: test13.yml
    loop: "{{ [1,2,3,4,5,6,7,8,9,10] }}"
      
