---
- hosts: all
  gather_facts: false
  vars:
     DiskThreshold: 5

  tasks:

  - name: run PS_Script
    ansible.windows.win_shell: C:\temp\PS_Scripts\FreeSpace.ps1

  - name: copy text
    ansible.windows.win_shell:
      Select-String -Path C:\temp\FreeSpace.txt -pattern "@{FreeSpace="
    register: freespace

  - name: read file, copy data to service
    set_fact: freediskspace={{ freespace.stdout_lines }}

  - name: trim rubbish
    set_fact: data1={{ freediskspace | regex_replace('.*=') | regex_replace ("'.*") }}

  - name: blah
    set_fact:
     uptime_above_limit:
       "{{ data1 | int) >= (disk_threshold | int) }}"

  - debug: debug
     msg: " Server only has {{ data1 }}GB free on the C Drive - Please delete some file "
   when: uptime_above_limit is false
