#   create files
#   read file
#
#   if set to zero - nothing
#   if set to one - do once
#   if set to two - do twice - etc
#

---
- hosts: all
  gather_facts: false
  vars:
    filepath: c:\temp\autoservicesnumber.txt

  tasks:

#  - name: copy PS1 files from Ansible node to host temp folder
#    ansible.windows.win_copy:
#      src: \\VBOXsvr\VM_Shared_Folder\PS_Scripts
#      dest: C:\temp
#      remote_src: yes
#    register: file_copy

#  - name: run PS_Script
#    ansible.windows.win_shell: C:\temp\PS_Scripts\AutoServices.ps1

  - name: copy text
    ansible.windows.win_shell:
      Select-String -Path C:\temp\autoservicesnumber.txt -pattern "Lines="
    register: loop

  - name: read file, copy data to service
    set_fact: service={{ loop.stdout_lines }}

  - name: remove everything apart from loop number
    set_fact: data1={{ service | regex_replace('.*=') | regex_replace ("'.*") }}

  - name: all services are now started
    ansible.builtin.debug:
      msg: "number of times to loop {{ data1 }}"
