---
- hosts: all
  gather_facts: false
  vars:
    num: 1
  tasks:

  - name: copy text
    ansible.windows.win_shell:
      Select-String -Path C:\temp\autoservices.txt -pattern "Service="
    register: service

  - name: debug1a
    ansible.builtin.debug:
      msg: "number = {{ num }}"

  - name: read file, copy data to service
    set_fact: service={{ service.stdout_lines [num] }}

  - name: debug for number 1
    ansible.builtin.debug:
      msg: "service = {{ service }} "

  - name: set fact
    set_fact: num="2"

  - name: debug2a
    ansible.builtin.debug:
      msg: "number = {{ num }}"

  - name: copy text
    ansible.windows.win_shell:
      Select-String -Path C:\temp\autoservices.txt -pattern "Service="
    register: service
    
  - name: read file, copy data to service
    set_fact: service={{ service.stdout_lines [num] }}

  - name: debug for number 2
    ansible.builtin.debug:
      msg: "service = {{ service }} "
