---
- hosts: all
  gather_facts: false
  vars:
  tasks:

  - name: set fact
    set_fact:
      service_name: "adaptor"

  - name: debug1
    debug:
      msg: "service contains IC3 {{ service_name }}"
    when: service_name == "ic3"

  - name: debug2
    debug:
      msg: "service does not contains IC3 {{ service_name }}"
    when: service_name != "ic3"
