#   create files
#   read file
#
#   if set to zero - nothing
#   if set to one - do once
#   if set to two - do twice - etc
#

---
- hosts: all
  gather_facts: false
  vars:
    filepath: c:\temp\autoservicesnumber.txt

  tasks:

#  - name: copy PS1 files from Ansible node to host temp folder
#    ansible.windows.win_copy:
#      src: \\VBOXsvr\VM_Shared_Folder\PS_Scripts
#      dest: C:\temp
#      remote_src: yes
#    register: file_copy

#  - name: run PS_Script
#    ansible.windows.win_shell: C:\temp\PS_Scripts\AutoServices.ps1

  - name: load data
    slurp:
      src: "{{ filepath }}"
    register: slurped_data

  - name: debug data
    debug: msg="the number of lines is {{ slurped_data }}"
#    with_lines: C:\temp\AutoServicesNumber.txt

#  - name: read file
#    set_fact: loops={{ service.stdout_lines }}

#  - name: all services are now started
#    ansible.builtin.debug:
#      msg: "number of times to loop {{ loops }}"
