---
- hosts: all
  gather_facts: false
  vars_prompt:
  - name: patch_number
    prompt: What is the patch number?
    private: no

  tasks:
  - name: Get server name
    ansible.windows.win_command: powershell.exe -
    args:
      stdin: hostname
    register: server_name

  - name: search file to see if the patch has been installed
    ansible.windows.win_shell:
      Select-String -Path C:\temp\PatchesInstalled.txt -pattern "{{ patch_number}}"
    register: patch

#  - debug:
#      msg: "patch1 is set to {{ patch1 }}"
#
  - name: read file to get free disk space
    set_fact: patch_installed={{ patch.stdout_lines }}

  - debug:
      msg: "patch_installed is set to {{ patch_installed }}"

  - name: copy disk space information from file
    ansible.windows.win_shell:
      Select-String -Path C:\temp\PatchesInstalled.txt -pattern "Installed="
    register: install_date

  - name: read file to get free disk space
    set_fact: installed_on={{ install_date.stdout_lines }}

  - name: trim file to get free disk space value
    set_fact: date={{ installed_on | regex_replace('.*=') | regex_replace ("'.*") }}

  - debug:
      msg: " {{ patch_number }} is installed on {{ server_name.stdout_lines[0] }} on {{ date }}"
    when: patch_installed|length > 2

  - debug:
      msg: " {{ patch_number }} is not installed on {{ server_name.stdout_lines[0] }}"
    when: patch_installed|length < 1
