---
- hosts: all
  gather_facts: false
  tasks:

    - name: copy file from Windows to Windows
      ansible.windows.win_copy:
        src: C:\temp\ian.txt
        dest: C:\temp\a\ian.txt
        remote_src: yes
