---
- hosts: all
  gather_facts: yes
  tasks:

  - name: debug1
    debug:
      msg: "ip is {{ ansible_ip_addresses }}"

  - name: set_fact
  #  set_fact: ip={{ ansible_ip_addresses }}
    set_fact: ip=192.168.1.250

  - name: debug
    debug:
      msg: "ip is {{ ip }}"

  - name: greater than 192.168.1.200
    debug:
      msg: "IP is greater than 192.168.1.200"
    when: ip == "192.168.1.250"     

#  - name: remove everything apart from service name
#    set_fact: service_name={{ service | regex_replace('.*=') | regex_replace ("'.*") }}
