---
- hosts: all
  gather_facts: false
  vars:
    patch: KB3192137
  tasks:

  - name: set the fact to "true"
    set_fact: patch_failed="true"

  - name: Uninstall hotfix with KB
    win_hotfix:
      hotfix_kb: "{{ patch }}"
      state: absent
    register: hotfix_uninstall
    ignore_errors: true

  - name: set fact to "false"
    set_fact: patch_failed="false"
    when: hotfix_uninstall.reboot_required == true or hotfix.uninstall.reboot_required == false
    ignore_errors: true

  - debug:
      msg: "Patch {{ patch }} failed to uninstall from {{ inventory_hostname }}, please investigate"
    when: patch_failed == true

  - debug:
      msg: "Patch {{ patch }} has been uninstalled from {{ inventory_hostname }} no reboot required"
    when: patch_failed == false and hotfix_uninstall.reboot_required == false

  - debug:
      msg: "Patch {{ patch }} has been uninstalled, rebooting {{ inventory_hostname }} now"
    when: patch_failed == false and hotfix_uninstall.reboot_required == true

  - name: reboot (if required)
    win_reboot:
    when: patch_failed == false and hotfix_uninstall.reboot_required == true
