---
- hosts: all
  gather_facts: false
  vars:
     days: 5
  tasks:
#
#   code which runs the powershell script, passing a variable from AT
#
  - name: run PS_Script
    win_shell: C:\temp\PS_Scripts\IMCVariabledays.ps1 {{ days }}
