---
- hosts: all
  gather_facts: True
  vars:
    lon02a: http://IFWQTV0100.TEST01GLOBAL.LLOYDSTSB.COM:8530
    lon02b: http://IFWQTV0101.TEST01GLOBAL.LLOYDSTSB.COM:8530
    lon06a: http://IFWQTV0200.TEST01GLOBAL.LLOYDSTSB.COM:8530
    lon06b: http://IFWQTV0201.TEST01GLOBAL.LLOYDSTSB.COM:8530
    rk2a: http://IFWQTV0300.TEST01GLOBAL.LLOYDSTSB.COM:8530 
    rk2b: http://IFWQTV0301.TEST01GLOBAL.LLOYDSTSB.COM:8530
    pb1a: http://IFWQTV0400.TEST01GLOBAL.LLOYDSTSB.COM:8530
    pb1b: http://IFWQTV0401.TEST01GLOBAL.LLOYDSTSB.COM:8530
  tasks:

  - name: nslookup the default gateway
#    shell: 'nslookup "{{ default_ipv4.gateway }}"'
    win_command: nslookup hostname
    register: nslookup_results
    ignore_errors: True
    args:
      warn: false

  - name: print
    debug:
      msg: "{{ nslookup_results.stdout }}"

  - name: set fact on host on the best location - LON02
    set_fact:
      WSUS_Server1: "{{ lon02a }}"
      WSUS_Server2: "{{ lon02b }}"
      cacheable: yes
    when: nslookup_results.stdout.find("nothing") != -1

  - name: set fact on host on the best location - LON06
    set_fact:
      WSUS_Server1: "{{ lon06a }}"
      WSUS_Server2: "{{ lon06b }}"
      cacheable: yes
    when: nslookup_results.stdout.find("eehub") != -1

  - name: set fact on host on the best location - RK2
    set_fact:
      WSUS_Server1: "{{ rk2a }}"
      WSUS_Server2: "{{ rk2b }}"
      cacheable: yes
    when: nslookup_results.stdout.find("rk2") != -1

  - name: set fact on host on the best location - PB1
    set_fact:
      WSUS_Server1: "{{ pb1a }}"
      WSUS_Server2: "{{ pb1b }}"
      cacheable: yes
    when: nslookup_results.stdout.find("pb") != -1

  - name: print the WSUS Servers to use for this server
    debug:
      msg:
        - "Primary server is {{ WSUS_Server1 }}"
        - "Secondary server is {{ WSUS_Server2 }}"

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: WUServer
      data: "{{ WSUS_Server1 }}"
      type: string

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: WUStatusServer
      data: "{{ WSUS_Server2 }}"
      type: string
