---
- hosts: all
  gather_facts: false
  tasks:
#
#   code to copy IMCMerge.PS1 to C:\TEMP\PS_Scripts on server
#
  - name: run PS_Script
    win_shell: C:\temp\PS_Scripts\IMCMerge.ps1

  - name: copy file from windows to centos
#   copies file to HOME/FILES/192.168.1.249/C:/TEMP/MergedData.zip
    fetch:
      src: C:/temp/MergedData.zip
      dest: /home/ian/files/
      remote_src: yes
