---
- hosts: all
  gather_facts: True
  vars:
    PRE-LIVE-PRI: http://IFWQTV0100.TEST01GLOBAL.LLOYDSTSB.COM:8530
    PRE-LIVE-ALT: http://IFWQTV0101.TEST01GLOBAL.LLOYDSTSB.COM:8530
    LON02-PRI: http://IFWLGV0104.GLOBAL.LLOYDSTSB.COM:8530
    LON06-PRI: http://IFWLGV0106.GLOBAL.LLOYDSTSB.COM:8530
    RK2-PRI: http://IFWLGV0107.GLOBAL.LLOYDSTSB.COM:8530
    PB1-PRI: http://IFWLGV0108.GLOBAL.LLOYDSTSB.COM:8530
    ALT: http://IFWLGV0103.GLOBAL.LLOYDSTSB.COM:8530
  tasks:

  - name: nslookup the default gateway
#    shell: 'nslookup "{{ default_ipv4.gateway }}"'
    win_command: nslookup hostname
    register: nslookup_results
    ignore_errors: True
    args:
      warn: false

  - name: print
    debug:
      msg: "{{ nslookup_results.stdout }}"

  - name: set fact on host on the best location - PRE-LIVE
    set_fact:
      WSUS_Server1: "{{ PRE-LIVE-PRI }}"
      WSUS_Server2: "{{ PRE-LIVE-ALT }}"
      cacheable: yes
    when: nslookup_results.stdout.find("anycast") != -1

  - name: set fact on host on the best location - LON02
    set_fact:
      WSUS_Server1: "{{ LON02-PRI }}"
      WSUS_Server2: "{{ ALT }}"
      cacheable: yes
    when: nslookup_results.stdout.find("lon02") != -1

  - name: set fact on host on the best location - LON06
    set_fact:
      WSUS_Server1: "{{ LON06-PRI }}"
      WSUS_Server2: "{{ ALT }}"
      cacheable: yes
    when: nslookup_results.stdout.find("lon06") != -1

  - name: set fact on host on the best location - RK2
    set_fact:
      WSUS_Server1: "{{ RK2-PRI }}"
      WSUS_Server2: "{{ ALT }}"
      cacheable: yes
    when: nslookup_results.stdout.find("rk2") != -1

  - name: set fact on host on the best location - PB1
    set_fact:
      WSUS_Server1: "{{ PB1-PRI }}"
      WSUS_Server2: "{{ ALT }}"
      cacheable: yes
    when: nslookup_results.stdout.find("eehub") != -1

  - name: print the WSUS Servers to use for this server
    debug:
      msg:
        - "Primary server is {{ WSUS_Server1 }}"
        - "Alternate server is {{ WSUS_Server2 }}"

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: WUServer
      data: "{{ WSUS_Server1 }}"
      type: string

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: WUStatusServer
      data: "{{ WSUS_Server1 }}"
      type: string

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: UpdateServiceURLAlternative
      data: "{{ WSUS_Server2 }}"
      type: string
