---
- hosts: all
  gather_facts: True
  vars:
    LON02-1: http://IFWQTV0100.TEST01GLOBAL.LLOYDSTSB.COM:8530
    LON02-2: http://IFWQTV0101.TEST01GLOBAL.LLOYDSTSB.COM:8530
    LON06-1: http://IFWQTV0200.TEST01GLOBAL.LLOYDSTSB.COM:8530
    LON06-2: http://IFWQTV0201.TEST01GLOBAL.LLOYDSTSB.COM:8530

  tasks:

  - name: nslookup the default gateway
    shell: 'nslookup "{{ ansible_default_ipv4.gateway }}"'
    register: nslookup_results
    ignore_errors: True
    args:
      warn: false
  - name: print
    debug:
      msg: "{{ nslookup_results.stdout }}"

  - name: set fact on host on the best location
    set_fact:
      WSUS_Server1: {{ LON02-1 }}
      WSUS_Server2: {{ LON02-2 }}
      cacheable: yes
    when: nslookup_results.stdout.find("nothing") != -1

  - name: set fact on host on the best location
    set_fact:
      WSUS_Server1: {{ LON06-1 }}
      WSUS_Server2: {{ LON06-2 }}
      cacheable: yes
    when: nslookup_results.stdout.find("asus") != -1

  - name: print the WSUS Servers to use for this server
    debug:
      msg:
        - "Primary server is {{ WSUS_Server1 }}"
        - "Secondary server is {{ WSUS_Server2 }}"

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: WUServer
      data: "{{ WSUS_Server1 }}"
      type: string

  - name: Amend/Add new key to the registry
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: WUStatusServer
      data: "{{ WSUS_Server2 }}"
      type: string
